#
# validate yml:
# circleci config validate
#
version: 2.1

#
# Orbs
#
orbs:
  tools: naturalcycles/tools@volatile
  # tools: naturalcycles/tools@dev:1

#
# Workflows
#
workflows:
  version: 2
  default-workflow:
    jobs:
      - tools/publish-job:
          filters:
            branches:
              only: master
      - tools/test-job
